services:
  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./volumes/mysql/init:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:${MAUTIC_EXPOSED_DB_PORT:-3306}:3306
    environment:
      - TZ=${TZ:-CET}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mautic}
      - MYSQL_USER=${MYSQL_USER:-mautic}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-mautic}
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  mautic_web:
    extends:
      file: ../../docker-compose.yml
      service: mautic_web
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 127.0.0.1:${MAUTIC_HTTP_PORT:-80}:80

  mautic_cron:
    extends:
      file: ../../docker-compose.yml
      service: mautic_cron

  mautic_worker:
    extends:
      file: ../../docker-compose.yml
      service: mautic_worker

  rabbitmq:
    image: rabbitmq:4
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST:-rabbitmq}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq
      - .docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 127.0.0.1:15672:15672
