x-mautic-volumes: &mautic-volumes
  - ./volumes/mautic:/var/www/html
  - ./volumes/cron:/opt/mautic/cron

x-mautic-environments: &mautic-environments
  MAUTIC_VERSION: ${MAUTIC_VERSION:-5.x-dev}
  TZ: ${TZ:-CET}
  HOST_UID: ${HOST_UID:-1000}
  HOST_GID: ${HOST_GID:-1000}
  MAUTIC_DB_HOST: ${MAUTIC_DB_HOST:-mysql}
  MAUTIC_DB_PORT: ${MAUTIC_DB_PORT:-3306}
  MAUTIC_DB_USER: ${MAUTIC_DB_USER:-mautic}
  MAUTIC_DB_PASSWORD: ${MAUTIC_DB_PASSWORD:-mautic}
  MAUTIC_DB_NAME: ${MAUTIC_DB_NAME:-mautic}
  MAUTIC_RUN_CRON_JOBS: ${MAUTIC_RUN_CRON_JOBS:-true}
  XDEBUG_CONFIG: ${XDEBUG_CONFIG:-}
  MAUTIC_MESSENGER_DSN_EMAIL: ${MAUTIC_MESSENGER_DSN_EMAIL:-amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:5672${RABBITMQ_DEFAULT_VHOST:-rabbitmq}}
  MAUTIC_MESSENGER_DSN_HIT: ${MAUTIC_MESSENGER_DSN_HIT:-amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:5672${RABBITMQ_DEFAULT_VHOST:-rabbitmq}}

services:
  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./volumes/mysql/init:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - TZ=${TZ:-CET}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mautic}
      - MYSQL_USER=${MYSQL_USER:-mautic}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-mautic}
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  mautic_web:
    image: ghcr.io/librecodecoop/mautic:${MAUTIC_VERSION:-5.x-dev}-${IMAGE_TYPE:-apache}
    # build:
    #   context: ../../.docker/
    #   dockerfile: Dockerfile.${IMAGE_TYPE:-apache}
    restart: unless-stopped
    volumes: *mautic-volumes
    environment:
      <<: *mautic-environments
      DOCKER_MAUTIC_LOAD_TEST_DATA: ${DOCKER_MAUTIC_LOAD_TEST_DATA:-false}
      DOCKER_MAUTIC_RUN_MIGRATIONS: ${DOCKER_MAUTIC_RUN_MIGRATIONS:-false}
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 127.0.0.1:${MAUTIC_HTTP_PORT:-80}:80

  mautic_cron:
    image: ghcr.io/librecodecoop/mautic:${MAUTIC_VERSION:-5.x-dev}-${IMAGE_TYPE:-apache}
    # build:
    #   context: ../../.docker/
    #   dockerfile: Dockerfile.${IMAGE_TYPE:-apache}
    restart: unless-stopped
    volumes: *mautic-volumes
    environment:
      <<: *mautic-environments
      DOCKER_MAUTIC_ROLE: mautic_cron
    depends_on:
      mautic_web:
        condition: service_healthy

  mautic_worker:
    image: ghcr.io/librecodecoop/mautic:${MAUTIC_VERSION:-5.x-dev}-${IMAGE_TYPE:-apache}
    # build:
    #   context: ../../.docker/
    #   dockerfile: Dockerfile.${IMAGE_TYPE:-apache}
    restart: unless-stopped
    volumes: *mautic-volumes
    environment:
      <<: *mautic-environments
      DOCKER_MAUTIC_ROLE: mautic_worker
    depends_on:
      mautic_web:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST:-rabbitmq}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    volumes: 
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq
      - .docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 127.0.0.1:15672:15672
