services:
  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./volumes/mysql/init:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:${MAUTIC_EXPOSED_DB_PORT:-3306}:3306
    environment:
      - TZ=${TZ:-CET}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mautic}
      - MYSQL_USER=${MYSQL_USER:-mautic}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-mautic}
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  mautic_web:
    extends:
      file: ../../docker-compose.yml
      service: mautic_web
    ports:
      - 127.0.0.1:${MAUTIC_HTTP_PORT:-80}:80
    depends_on:
      mysql:
        condition: service_healthy

  mautic_cron:
    extends:
      file: ../../docker-compose.yml
      service: mautic_cron

  mautic_worker:
    extends:
      file: ../../docker-compose.yml
      service: mautic_worker